#!/usr/bin/env bash
# Regenerate the "## Packages" table in README.md from src/packages.dhall, the
# single source of truth for fork versions. The table lives between the
# `<!-- BEGIN PACKAGE TABLE ... -->` / `<!-- END PACKAGE TABLE -->` markers.
#
#   scripts/gen-readme-table.sh           # rewrite README.md in place
#   scripts/gen-readme-table.sh --check   # exit 1 if README.md is out of date
#
# Self-contained: pulls dhall-to-json + jq from nixpkgs, so it needs no repo
# flake or dev shell.
set -euo pipefail
cd "$(dirname "$0")/.."

readme="README.md"
begin='<!-- BEGIN PACKAGE TABLE (generated by scripts/gen-readme-table.sh from src/packages.dhall — do not edit by hand) -->'
end='<!-- END PACKAGE TABLE -->'

rows="$(
  nix shell nixpkgs#dhall-json nixpkgs#jq --accept-flake-config -c bash -c '
    dhall-to-json --file src/packages.dhall \
      | jq -r "to_entries | sort_by(.key)[]
               | \"| \(.key) | \(.value.repo | sub(\"\\\\.git$\"; \"\")) | \(.value.version) |\""
  '
)"

table="$begin
| Package | Repository | Version |
|---|---|---|
$rows
$end"

# Splice the table between the markers, leaving the rest of README untouched.
new="$(awk -v table="$table" -v b="$begin" -v e="$end" '
  $0 == b { print table; skip = 1; next }
  $0 == e { skip = 0; next }
  !skip   { print }
' "$readme")"

if [[ "${1:-}" == "--check" ]]; then
  if ! diff -u "$readme" <(printf '%s\n' "$new") >/dev/null; then
    echo "README.md package table is out of date. Run scripts/gen-readme-table.sh." >&2
    diff -u "$readme" <(printf '%s\n' "$new") >&2 || true
    exit 1
  fi
  echo "README.md package table is in sync with src/packages.dhall."
else
  printf '%s\n' "$new" >"$readme"
  echo "Wrote $readme package table from src/packages.dhall."
fi
